# Generated by Django 3.1.6 on 2021-02-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrrequest',
            name='patient_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
